name: Build and Release

permissions:
  contents: write
on:
  push:
    tags:
      - 'v*.*.*'  # 假设您的标签遵循语义版本控制

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: libseu_lex.a
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: seu_lex.lib
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          override: true
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: Build staticlib
        run: cargo build --release --target ${{ matrix.target }}
        env:
          CARGO_TERM_COLOR: always
      - name: Rename & Move the artifact
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/${{ matrix.asset_name }} artifacts/
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
              artifacts/libseu_lex.a/libseu_lex.a
              artifacts/seu_lex.lib/seu_lex.lib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
